#!/usr/bin/env bash
# cleanup_flatpak.sh - Remove every artefact build_flatpak.sh produces.
#
# Scoped to the Flatpak build ALONE. The Nuitka executable (buildexe.py) and the
# Windows installer (buildinstaller.py) write elsewhere and are deliberately
# left untouched, so the three delivery paths stay independent and cleaning one
# never costs another a rebuild. frontend/dist is left alone for the same
# reason: run-edca-built.sh and the Windows build both use it.
#
# build_flatpak.sh installs the app as its normal course, so a cleanup that left
# it installed would not be a cleanup: it undid the artefacts and kept the one
# thing that is actually on the machine. Uninstalling is therefore the default
# and matches the sibling script's shape (bundle by default, --no-bundle to opt
# out). Pass --keep-installed to clear the build artefacts and keep the app.
#
# The application's own data is never removed without being asked for. A
# database rebuilt from the journal costs minutes of ingestion and the saved
# journal directory is the one setting the user had to find, so --purge-data is
# opt-in rather than part of a routine clean.
#
# Usage:
#   ./cleanup_flatpak.sh                  - remove artefacts AND uninstall the app
#   ./cleanup_flatpak.sh --keep-installed - remove artefacts only, app stays
#   ./cleanup_flatpak.sh --purge-data     - also delete the app's user data

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

APP_ID="uk.co.oernster.EDColonisationAsst"
BUNDLE="edcolonisationasst.flatpak"
MANIFEST="${APP_ID}.yml"
USER_DATA="${HOME}/.var/app/${APP_ID}"

UNINSTALL=1
PURGE_DATA=0
for arg in "$@"; do
    case "$arg" in
        --keep-installed) UNINSTALL=0 ;;
        --purge-data)     PURGE_DATA=1 ;;
        *)
            echo "Unknown option: ${arg}" >&2
            echo "Usage: $0 [--keep-installed] [--purge-data]" >&2
            exit 1
            ;;
    esac
done

echo "Cleaning Flatpak build artefacts..."

# Generated by build_flatpak.sh: the builder trees, the local repo, the
# pre-downloaded wheels, the self-generated manifest and the packaging helpers
# (launcher, desktop entry, metainfo and the derived icon set). None is
# committed, so removing them loses nothing that is not regenerated.
rm -rf .flatpak-build .flatpak-repo .flatpak-builder .flatpak-wheels
rm -rf packaging
rm -f "${MANIFEST}"
rm -f "${BUNDLE}"

echo "  Removed build trees, wheels, manifest, packaging helpers and bundle."

if [[ $UNINSTALL -eq 1 ]]; then
    if flatpak info --user "${APP_ID}" &>/dev/null; then
        echo "Uninstalling ${APP_ID}..."
        flatpak uninstall --user --noninteractive "${APP_ID}"
        echo "  Uninstalled."
    else
        echo "  ${APP_ID} is not installed for this user; nothing to uninstall."
    fi
else
    echo "  App left installed (--keep-installed)."
fi

if [[ $PURGE_DATA -eq 1 ]]; then
    if [[ -d "${USER_DATA}" ]]; then
        echo "Deleting user data at ${USER_DATA} ..."
        echo "  This removes the colonisation database, the saved journal"
        echo "  directory and the runtime log."
        rm -rf "${USER_DATA}"
        echo "  Deleted."
    else
        echo "  No user data at ${USER_DATA}; nothing to purge."
    fi
else
    if [[ -d "${USER_DATA}" ]]; then
        echo "  User data kept at ${USER_DATA} (pass --purge-data to delete it)."
    fi
fi

echo "Done."
